/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './frontend/**/*.html',
    './frontend/**/*.js',
    '!./frontend/vendor/**',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#ff2d78',
        'secondary': '#00ffcc',
        'tertiary': '#ffe04a',
        'background': '#0a0a12',
        'surface': '#0f0f1a',
        'surface-container': '#141422',
        'surface-container-low': '#111118',
        'surface-container-high': '#1e1e30',
        'surface-container-highest': '#28283e',
        'surface-container-lowest': '#0a0a12',
        'surface-bright': '#1a1a2e',
        'surface-dim': '#0f0f1a',
        'surface-variant': '#1e1e30',
        'surface-tint': '#ff2d78',
        'on-background': '#e8e0f0',
        'on-surface': '#e8e0f0',
        'on-surface-variant': '#a098b0',
        'on-primary': '#1a0010',
        'on-secondary': '#001a1a',
        'on-tertiary': '#1a1000',
        'primary-container': '#b3004e',
        'secondary-container': '#004d3d',
        'tertiary-container': '#665200',
        'on-primary-container': '#ffe0ec',
        'on-secondary-container': '#c0fff4',
        'on-tertiary-container': '#fff0c0',
        'primary-fixed': '#ffe0ec',
        'primary-fixed-dim': '#ff80aa',
        'secondary-fixed': '#c0fff4',
        'secondary-fixed-dim': '#00e6b8',
        'tertiary-fixed': '#fff0c0',
        'tertiary-fixed-dim': '#ffe04a',
        'outline': '#5a5068',
        'outline-variant': '#302840',
        'error': '#ff4444',
        'error-container': '#3d0f0f',
        'on-error': '#1a0000',
        'on-error-container': '#ffa0a0',
        'inverse-surface': '#e8e0f0',
        'inverse-on-surface': '#0a0a12',
        'inverse-primary': '#8c0038',
        'on-primary-fixed': '#3d0020',
        'on-primary-fixed-variant': '#8c0038',
        'on-secondary-fixed': '#001a1a',
        'on-secondary-fixed-variant': '#004d4d',
        'on-tertiary-fixed': '#1a1000',
        'on-tertiary-fixed-variant': '#665200',
      },
      fontFamily: {
        'headline': ['Sora', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Space Grotesk', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        '2xl': '0.75rem',
        'full': '9999px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
